{% set name = "bgcArgoDMQC" %}
{% set version = "0.2.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bgcArgoDMQC-{{ version }}.tar.gz
  sha256: 9e69abd3e75c3e673c7a31ace9b3e72401ea5b478475dba211705936562fab53

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - cmocean
    - gsw
    - matplotlib-base
    - netcdf4
    - numpy
    - pandas
    - python >=3.4
    - scipy
    - seaborn

test:
  imports:
    - bgcArgoDMQC
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ArgoCanada/bgcArgoDMQC
  summary: A python library for quality control of BGC-Argo data
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - cgrdn
